services:
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb -p local/generated || true &&
        mc mb -p local/uploads || true &&
        mc anonymous set download local/uploads &&
        mc ls local
      "
    restart: "no"
